name = "party"
version = "1.0.0"
description = "A little parser combinator library"

licences = ["GPL-3.0-or-later"]
repository = { type = "github", user = "RyanBrewer317", repo = "party" }
gleam = ">= 0.32.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36"

[dev-dependencies]
gleeunit = "~> 0.10"
