name = "party"
version = "1.0.3"
description = "A little parser combinator library in Gleam."

licences = ["MPL-2.0"]
repository = { type = "github", user = "RyanBrewer317", repo = "party" }
gleam = ">= 0.32.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36" # 0.36 <= version < 0.37

[dev-dependencies]
gleeunit = ">= 0.10.0"
