name = "party"
version = "0.1.2"
description = "A little parser combinator library"

licences = ["GPL-3.0-or-later"]
repository = { type = "github", user = "RyanBrewer317", repo = "party" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.30"

[dev-dependencies]
gleeunit = "~> 0.10"
