name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          gleam-version: "1.0.0"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
